### ISSUE TITLE
Creating DB Queries for creating the table and commit those queries on GIT

### ISSUE THREAD

**Issue by krishnanvignesh** [Scaler-Community-Projects/NGO-Farmer-Analysis#21]
Task:

* Creating DB Queries for creating the table and commit those queries on GIT. 

Note: Please assign the task to yourself and start working on it.

**Comment by krishnanvignesh** [comment]
I guess this was completed? @shubh-07 should I close this?

**Comment by mephi007** [comment]
raised Pr #63
