### ISSUE TITLE
Add PRD in README

### ISSUE THREAD

**Issue by ritesh-pandey** [Scaler-Community-Projects/NGO-Farmer-Analysis#34]
Add product description in README file. It will act as our Product Requirements Document (PRD).

A PRD outlines the requirements of what you’re going to build so that people know what the completed product should do. 

PRDs typically include the following:
- Purpose — Who it’s for and why you’re building it.
- Features — What you’re going to build.

## Purpose
-   What problems this product solves.
-   Who will use the product.
-   Why it’s important.

## Features
This step is to determine the feature requirements for the release. Every feature should support the overall purpose of  product.

**Comment by ritesh-pandey** [comment]
We can use this source 
https://docs.google.com/document/d/1jeb5iTOLGwgD3fr9S312jCWTmPz5wAeWyKVz1eY_vKU/edit

Useful links to refer for documentation
- https://github.com/ushahidi/platform An organisation for collecting data at grass-root level. Have a look at its documentation. It describes what it does very clearly.  
- https://github.com/project-travel-mate/Travel-Mate An app for travel enthusiasts. Refer its readme file.

**Comment by krishnanvignesh** [comment]
I guess we can add a contribution file link to our main Readme.md file?

**Comment by ritesh-pandey** [comment]
I think @krishnanvignesh you can pick this one.

**Comment by krishnanvignesh** [comment]
> I think @krishnanvignesh you can pick this one.

ok, will assign it to me.
