### ISSUE TITLE
Create adoption form

### ISSUE THREAD

**Issue by ritesh-pandey** [Scaler-Community-Projects/NGO-Farmer-Analysis#35]
Create form with fields mentioned in wiki. Use React Bootstrap Form component for design.

https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Adoption-Form

**Comment by 94151** [comment]
I want to work on this.

**Comment by Epsilon0910** [comment]
I want to work on this too

**Comment by crayx** [comment]
I want to work on this .

**Comment by ritesh-pandey** [comment]
> I want to work on this too

Let us choose any other task.

**Comment by ritesh-pandey** [comment]
> I want to work on this .

Already assigned you on a different task.

**Comment by ritesh-pandey** [comment]
@94151 Any progress on this?

**Comment by krishnanvignesh** [comment]
reassigning as there is no response. @crayx or @charchitjoshidot woud you like to work on this?

**Comment by crayx** [comment]
I would like to take this issue .

**Comment by crayx** [comment]
Are there any changes that I need to fix?
Attaching 2 screenshots of the form.

![Screenshot 2020-07-14 at 3 43 48 PM](https://user-images.githubusercontent.com/37878891/87414152-f6af7580-c5e8-11ea-9872-8ce2de5b553c.png)
![Screenshot 2020-07-14 at 3 42 07 PM](https://user-images.githubusercontent.com/37878891/87414156-f911cf80-c5e8-11ea-8fe6-8f7238f0659b.png)

**Comment by krishnanvignesh** [comment]
> Are there any changes that I need to fix?
> Attaching 2 screenshots of the form.
> 
>![Screenshot 2020-07-14 at 3 43 48 PM](https://user-images.githubusercontent.com/37878891/87414152-f6af7580-c5e8-11ea-9872-8ce2de5b553c.png)
> ![Screenshot 2020-07-14 at 3 42 07 PM](https://user-images.githubusercontent.com/37878891/87414156-f911cf80-c5e8-11ea-8fe6-8f7238f0659b.png)

I think the **Video Name** field should come in the last and should only be visible when **Adoption by** has Video checked.

**Comment by crayx** [comment]
Okay I will make the changes

**Comment by crayx** [comment]
1. I had a doubt that anyhow the farmer will be shown a video and it should be present in the table .
2. Then over that video they can assess whether over the shown video which option did the farmer chose.
3. The meeting or the video that was shown.
4. So should I show the video field only on the selected adoption value? because by doing that only the selected video will be collected , the ones that were not chosen would be left.

**Comment by krishnanvignesh** [comment]
> 1. I had a doubt that anyhow the farmer will be shown a video and it should be present in the table .
> 2. Then over that video they can assess whether over the shown video which option did the farmer chose.
> 3. The meeting or the video that was shown.
> 4. So should I show the video field only on the selected adoption value? because by doing that only the selected video will be collected , the ones that were not chosen would be left.

1. Showing a video is not a necessity. think in this way
4. this questions is confusing. we want to record only those videos that have been used in the meeting right?

**Comment by crayx** [comment]
Yes now I am also getting confused. Let's discuss this question in the
meeting then .

**Comment by ritesh-pandey** [comment]
@crayx 's point is that there can be a case where multiple videos are shown to a farmer and he chooses one among them for adoption. `Video name` becomes a required field only after `Mode of adoption` chosen was `video`.

Regarding multiple videos, @krishnanvignesh let us get clarity from Ayushi.
