### ISSUE TITLE
Create CRUD routes for adoption form

### ISSUE THREAD

**Issue by ritesh-pandey** [Scaler-Community-Projects/NGO-Farmer-Analysis#36]
Form details need to be saved in database. Create routes for the same. These routes will be invoked by client application.

Refer to wiki for more details.
https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Adoption-Form

**Comment by Medha08** [comment]
I and Anirban Chakraborty would like would like to work on this issue

**Comment by discoveranirban** [comment]
Yes! We both would like to contribute for this Issue.

**Comment by mephi007** [comment]
I would like work on this.

**Comment by ritesh-pandey** [comment]
> I would like work on this.

See if you can collaborate with @Medha08 and @discoveranirban . Else let us choose other issue.

**Comment by mephi007** [comment]
@Medha08  @discoveranirban  can i collaborate with you guys?

**Comment by ritesh-pandey** [comment]
To be clear, this issue only deals about creating end points and not the implementation.

So end result should be that we have:
- create end point
- read end point
- update end point
- delete end point

They will contain empty methods as of now.

Read best practices in naming these RESTful API.
