### ISSUE TITLE
Create layout/theme for application

### ISSUE THREAD

**Issue by ritesh-pandey** [Scaler-Community-Projects/NGO-Farmer-Analysis#37]
We need to have a theme for our application. All elements such as form, dialogue boxes etc. should follow it. It will give the application a coherency.

Create layout file which will include
- Top navigation
- Footer

Use Bootstrap components as much as possible.

**Comment by crayx** [comment]
I want to work on this .

**Comment by shubhipuntambekar** [comment]
I also want to work on this

**Comment by ritesh-pandey** [comment]
There are few unassigned issues. Did you have a look at them?

Let us work on issues individually as much as possible. I will create more issues if required.

**Comment by crayx** [comment]
![Screenshot 2020-07-05 at 7 07 02 PM](https://user-images.githubusercontent.com/37878891/86534108-63dd4f80-bef3-11ea-8313-199099893ddd.png)
Does this looks fine?
