### ISSUE TITLE
Create dissemination details form

### ISSUE THREAD

**Issue by ritesh-pandey** [Scaler-Community-Projects/NGO-Farmer-Analysis#39]
Please refer

https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Dissemination-Form

Implement the first part of form - dissemination details.

**Comment by jyotimourya** [comment]
I want to work on this.

**Comment by ritesh-pandey** [comment]
@jyotimourya Any progress on this?

**Comment by crayx** [comment]
@ritesh-pandey  @krishnanvignesh Can I work on this issue?

**Comment by krishnanvignesh** [comment]
> @ritesh-pandey @krishnanvignesh Can I work on this issue?

reassigning due to no response.

**Comment by crayx** [comment]
Yes @krishnanvignesh I will make sure that the PR gets closed first in future .

**Comment by crayx** [comment]
@ritesh-pandey @krishnanvignesh Attaching the ScreenShot of the dissemination details form  for the review.

![Screenshot 2020-07-16 at 3 44 04 PM](https://user-images.githubusercontent.com/37878891/87659489-458d1480-c77b-11ea-95fe-df2d3e628276.png)

**Comment by krishnanvignesh** [comment]
> @ritesh-pandey @krishnanvignesh Attaching the ScreenShot of the dissemination details form for the review.
> 
> ![Screenshot 2020-07-16 at 3 44 04 PM](https://user-images.githubusercontent.com/37878891/87659489-458d1480-c77b-11ea-95fe-df2d3e628276.png)

Looks good!
