### ISSUE TITLE
Create CRUD endpoints for dissemination details

### ISSUE THREAD

**Issue by ritesh-pandey** [Scaler-Community-Projects/NGO-Farmer-Analysis#40]
Dissemination form will be stored in two parts. First dissemination details will be created. Next farmer/attendee details will be stored and they will be mapped with a particular dissemination.

Create endpoints for the same.

Refer
https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Dissemination-Form

**Comment by bhatiaPankaj** [comment]
Would like to contribute to this issue but would require someone experienced in node to team up (I am in learning phase of node)

**Comment by mephi007** [comment]
would like to contribute to this issue, I learning too, but i think i can do it.

**Comment by ritesh-pandey** [comment]
@mephi007 and @bhatiaPankaj please collaborate on this one.

**Comment by krishnanvignesh** [comment]
> would like to contribute to this issue, I am learning too, but i think i can do it.
> Reading https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Dissemination-Form what I can speculate is that, as this form would be in two parts, and for one single meeting there could be many Attendee. So there should be two table different table, lets say "Meeting table" and "Attendee table". and to fill these two table, we can use two different endpoints, but "Attendee Table" has to use a key from "Meeting Table".
> Please correct me, if i have gone wrong anywhere. @krishnanvignesh @ritesh-pandey @shubh-07 @srkeshav

but I still don't understand the need for two different tables here. could you elaborate? like what kind of fields you'll have in those tables?

**Comment by mephi007** [comment]
@krishnanvignesh Im not sure with the part having **FORM IN TWO PARTS**. can you help me with that?

**Comment by mephi007** [comment]
@ritesh-pandey  @krishnanvignesh Present Schema for the meetings is not according to https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Dissemination-Form.

**Comment by krishnanvignesh** [comment]
> @ritesh-pandey @krishnanvignesh Present Schema for the meetings is not according to https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Dissemination-Form.

That's why this issue: [#41 ](https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/issues/41) has been created @mephi007

**Comment by ritesh-pandey** [comment]
There are two parts in dissemination form - meta data about meeting and attendee details. I believe we should store them separately. 

Also we should give flexibility to user to create them independently. Only condition being the attendee should be part of a meeting.

Flow will be:
1. User creates dissemination meta data
2. User creates attendee which were part of a particular dissemination

This way we are not forcing user to fill everything in one go.

Please give your opinion.
