### ISSUE TITLE
Create attendee - dissemination mapping

### ISSUE THREAD

**Issue by ritesh-pandey** [Scaler-Community-Projects/NGO-Farmer-Analysis#41]
Every farmer/attendee can belong to one or more dissemination. Define the schema to support this relation.

Refer
https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Dissemination-Form

**Comment by bhatiaPankaj** [comment]
Hi @ritesh-pandey . Added a table named dissemination_attendee_mapping which contains references to farmer,question and adoption. The schema is updated. Does this look good?
Also please assign the issue to me, I am unable to assign it to myself.

**Comment by krishnanvignesh** [comment]
> Hi @ritesh-pandey . Added a table named dissemination_attendee_mapping which contains references to farmer,question and adoption. The schema is updated. Does this look good?
> Also please assign the issue to me, I am unable to assign it to myself.

Pankaj could you please list the table fields?

**Comment by bhatiaPankaj** [comment]
> > Hi @ritesh-pandey . Added a table named dissemination_attendee_mapping which contains references to farmer,question and adoption. The schema is updated. Does this look good?
> > Also please assign the issue to me, I am unable to assign it to myself.
> 
> Pankaj could you please list the table fields?

Following are the fields in the dissemination_attendee_mapping  table.
event_id(PK)
farmer_id  (FK)
question_id (FK)
adoption_id(FK)
dissemination_id(FK)

Also the schema is the PR #59 has updated schema which could be of help.

**Comment by krishnanvignesh** [comment]
closing this issue as the PR is merged.
