### ISSUE TITLE
Create dissemination attendee form

### ISSUE THREAD

**Issue by ritesh-pandey** [Scaler-Community-Projects/NGO-Farmer-Analysis#42]
Refer
https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Dissemination-Form

We need to implement the part 2 of this document - attendee/farmer details.

**Comment by shubhipuntambekar** [comment]
I want to work on this

**Comment by shubhipuntambekar** [comment]
<img width="949" alt="Capture" src="https://user-images.githubusercontent.com/25868253/86580723-b6bf1180-bf9c-11ea-8369-ab27afc8feb2.PNG">


Please suggest for any changes in this form regarding layout / input types or anything else that needs to be corrected?

**Comment by ritesh-pandey** [comment]
Nice work. 

Few suggestions:
- You can use radio buttons for `Adoption wish`
- `Questions asked by farmer` can be a textarea
