### ISSUE TITLE
Implement Create dissemination

### ISSUE THREAD

**Issue by krishnanvignesh** [Scaler-Community-Projects/NGO-Farmer-Analysis#53]
Dissemination form will be stored in two parts. First dissemination details will be created. Next farmer/attendee details will be stored and they will be mapped with particular dissemination.

    * Dissemination details
        Date of dissemination
        Start time
        End time
        Place
        Name of video
        Name of Gram Panchayat
        Name of CRP
        Name of Village

    * Attendee details
        Farmer's name
        Husband's/Father's name
        Collectives name
        Adoption wish/Willing to adopt
        Questions asked by the farmer

    * Implement field validations for each field

Note:
Please go through the created endpoints before you start working on this. 

Refer: [issue #40](https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/issues/40)
[https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Dissemination-Form](https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Dissemination-Form)

**Comment by bhatiaPankaj** [comment]
would like to take this up as I have worked on dissemination endpoints too.

**Comment by mephi007** [comment]
I would like to work on this along with Pankaj?
