### ISSUE TITLE
Implement Read dissemination

### ISSUE THREAD

**Issue by krishnanvignesh** [Scaler-Community-Projects/NGO-Farmer-Analysis#54]
You need to implement fetching the disseminations details. it will be having to types
    - fetch all disseminations in a table format
    - fetch single dissemination in form format

Note:
Please go through the created endpoints before you start working on this. 

Refer: [issue #40](https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/issues/40)
[https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Dissemination-Form](https://github.com/Scaler-Community-Projects/NGO-Farmer-Analysis/wiki/Dissemination-Form)

**Comment by bhatiaPankaj** [comment]
would like to contribute to this.

**Comment by krishnanvignesh** [comment]
> would like to contribute to this.

I have assigned you on another issue? do you want me to assign this too?

**Comment by ritesh-pandey** [comment]
@mephi007 Have a look at this one.

**Comment by mephi007** [comment]
I would like to work on this issue?

**Comment by mephi007** [comment]
Not able to assign myself!

**Comment by krishnanvignesh** [comment]
> Not able to assign myself!

I have assigned it!
